# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd06aee0dd6f46638cb51e45e9fa31586cc8db03d5f239f053f241219f4c3139c30c9d0b35d681855890079e9cc8bdd5d4ed17b8b4fe970149f2dd879f35a2d0

test:
  secret_key_base: e0795aace6b7e9973d4d54fee77e0e0d4ecc9a433081babb1aadb4aded4f8f418c57338ea25d5959509e62a552368dd4ab425389aabd08ab85abecc5b6fced8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
